# General configuration
pygments: true
rdiscount: true
permalink: /p/:title
paginate: 5

##
## Blog definitions
##

# Required
# Blog title and description/subtitle
title: Weekend codes
description: Codes and random stuff I am up to share with you

# Required
# Absolute base URL for this site _without_ trailing slash
url: http://stockrt.github.com

# Required
# Absolute URL of the feed
# You may want to change this URL to point to a feedburner feed
#feed: http://stockrt.github.com/atom.xml
feed: http://feeds.feedburner.com/weekendcodes

# Optional
# Author element in atom feed and meta
# If email is supplied, name is needed
author:
    postedby: false
    name: Rogério Schneider
    email: stockrt@gmail.com

# Optional
# Limit the more posts listing in the sidebar
more_posts:
    enable: true
    limit: 12

# Required
# Limit for related posts listing
related_posts_limit: 5

# Optional
# Helps to bypass Expires and Cache-Control in the Browser cache
# ttl minimum value is 60
cache_invalidation:
    enable: true
    # ttl is Required
    ttl: 300

# Optional
# A listing of your GitHub projects
# http://drnic.github.com/github-badges
github_badge:
    enable: true
    username: stockrt
    length: 8
    head: div
    #head: h2
    theme: white
    #theme: black
    title: My Projects
    showall: Show all
    showfork: 0
    #showfork: 1

##
## Search and Tracking elements
##

# Optional
# http://www.google.com/cse
google_cse:
    enable: true
    # id is Optional
    # You can get one here: http://www.google.com/cse
    id: 000162502351056619788:rgh3bxf1v7e

# Optional
# http://www.google.com/analytics
google_analytics:
    enable: true
    # tracker_id is Required
    tracker_id: UA-5567404-4

# Optional
# http://tracker.icerocket.com
icerocket:
    enable: true
    project_id: 29519

##
## Social elements
##

# Optional
# http://disqus.com
disqus:
    enable: true
    # shortname is Required
    shortname: weekendcodes
    # permalink_is_a_directory is Required.
    # If you point your permalink to a directory (that, of course, contains an
    # auto-generated index.html inside) you should set this to true, if not,
    # set to false.
    #permalink_is_a_directory: false
    permalink_is_a_directory: true

# Optional
# http://sharethis.com
sharethis: <script type="text/javascript" src="http://w.sharethis.com/button/sharethis.js#publisher=829268d1-9084-47c1-9ae8-7164387fe686&amp;type=website&amp;embeds=true"></script>

# Optional
# http://www.addthis.com
addthis:
    # username is Required
    username: stockrt
    subscribe: true
    toolbox: true

##
## Other sidebar elements
##

# Optional
links:
    - name: Projects
      url: http://stockrt.github.com/projects
    - name: Directory listing at home
      url: http://stockrtweb.homelinux.com

# Optional
blogroll:
    - name: Petryx (Marlon Petry)
      url: http://petryx.blogrs.com.br
    - name: Nardol (Pablo Lorenzzoni)
      url: http://nardol.org
    - name: Ahã... programando...! (Leonir Zimmermann)
      url: http://ahaprogramando.wordpress.com
    - name: Akita on Rails (Fábio Akita)
      url: http://akitaonrails.com
    - name: Nome do Jogo (Carlos Brando)
      url: http://www.nomedojogo.com
    - name: High Scalability | Building bigger, faster, more reliable websites.
      url: http://highscalability.com
    - name: Joel on Software
      url: http://www.joelonsoftware.com

# Reference:
# http://github.com/vilcans/scribbish-jekyll
# http://quotedprintable.com/pages/scribbish
# http://github.com/mojombo/jekyll
# http://daringfireball.net/projects/markdown/syntax
# http://www.yaml.org
# http://www.liquidmarkup.org

# Jekyll:
# gem install mojombo-jekyll
