rdiscount: true
pygments: true

title: Rogério Schneider - Weekend coding blog
subtitle: Weekend codes I made and hosted on GitHub to share with you

# Absolute base URL for this site without trailing slash
url: http://stockrt.github.com/blog

# Absolute URL of feed.
# You may want to change this URL to point to a feedburner feed.
feed: http://stockrt.github.com/blog/atom.html

# Author element in atom feed. Optional.
# If email is supplied, name is required.
author:
    name: Rogério Schneider
    email: stockrt@gmail.com

#http://quotedprintable.com/pages/scribbish
#http://github.com/vilcans/scribbish-jekyll
