# General configuration
pygments: true
rdiscount: true
permalink: /p/:title
paginate: 1

# Blog title and subtitle
title: Rogério Schneider - Weekend coding
subtitle: Weekend codes I made and hosted on GitHub to share with you

# Absolute base URL for this site without trailing slash
url: http://stockrt.github.com/blog

# Absolute URL of feed
# You may want to change this URL to point to a feedburner feed
feed: http://stockrt.github.com/blog/atom.html

# Author element in atom feed. Optional.
# If email is supplied, name is required.
author:
    name: Rogério Schneider
    email: stockrt@gmail.com

google_analytics: |
    <script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    </script>
    <script type="text/javascript">
    try {
    var pageTracker = _gat._getTracker("UA-5567404-4");
    pageTracker._trackPageview();
    } catch(err) {}
    </script>

# Reference:
# http://quotedprintable.com/pages/scribbish
# http://github.com/vilcans/scribbish-jekyll
# TODO: google-analytics
# http://tracker.icerocket.com/project.create.php
# http://sharethis.com/
