# General configuration
pygments: true
rdiscount: true
permalink: /p/:title
paginate: 10

##
## Blog definitions
##

# Required
# Blog title and description
title: Weekend codes
description: Codes and random stuff I am up to share with you

# Required
# Absolute base URL for this site _without_ trailing slash
url: http://stockrt.github.com

# Required
# Absolute URL of the feed
# You may want to change this URL to point to a feedburner feed
#feed: http://stockrt.github.com/atom.xml
feed: http://feeds.feedburner.com/weekendcodes

# Optional
# Author element in atom feed
# If email is supplied, name is needed
author:
    name: Rogério Schneider
    email: stockrt@gmail.com

##
## Search and Tracking elements
##

# Optional
google_cse:
    enable: true
    # id is Optional
    id: 000162502351056619788:rgh3bxf1v7e

# Optional
google_analytics:
    enable: true
    # tracker_id is Required
    tracker_id: UA-5567404-4

##
## Social elements
##

# Optional
disqus:
    enable: true
    # shortname is Required
    shortname: weekendcodes
    # permalink_is_a_directory is Required.
    # If you point your permalink to a directory (that, of course, contains an
    # auto-generated index.html inside) you should set this to true, if not,
    # set to false.
    #permalink_is_a_directory: false
    permalink_is_a_directory: true

# Optional
sharethis: <script type="text/javascript" src="http://w.sharethis.com/button/sharethis.js#publisher=829268d1-9084-47c1-9ae8-7164387fe686&amp;type=website&amp;embeds=true"></script>

# Optional
#addthis_toolbox: |
#    <div class="addthis_toolbox addthis_default_style">
#    <a href="http://www.addthis.com/bookmark.php?v=250&amp;pub=stockrt" class="addthis_button_compact">Share</a>
#    </div>
#    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js?pub=stockrt"></script>

# Optional
addthis_subscribe: <a href="http://www.addthis.com/feed.php?pub=stockrt&amp;h1=http%3A%2F%2Ffeeds.feedburner.com%2Fweekendcodes&amp;t1=" onclick="return addthis_open(this, 'feed', 'http://feeds.feedburner.com/weekendcodes')" alt="Subscribe using any feed reader!" target="_blank"><img src="http://s7.addthis.com/static/btn/sm-feed-en.gif" width="83" height="16" alt="Subscribe" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js?pub=stockrt"></script>

##
## Sidebar elements
##

# Optional
links:
    - name: Projects
      url: http://stockrt.github.com/projects
    - name: Directory listing at home
      url: http://stockrtweb.homelinux.com

# Optional
blogroll:
    - name: Petryx (Marlon Petry)
      url: http://petryx.blogrs.com.br
    - name: Nardol (Pablo Lorenzzoni)
      url: http://nardol.org
    - name: Ahã... programando...! (Leonir Zimmermann)
      url: http://ahaprogramando.wordpress.com

# Reference:
# http://github.com/vilcans/scribbish-jekyll
# http://quotedprintable.com/pages/scribbish
# http://github.com/mojombo/jekyll
# http://daringfireball.net/projects/markdown/syntax
# http://www.yaml.org
